"""update devices model

Revision ID: 21fe7d6247a2
Revises: 2fd4dcb63b89
Create Date: 2025-11-22 21:12:38.712455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fe7d6247a2'
down_revision: Union[str, None] = '2fd4dcb63b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('catalog_manufacturer_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('catalog_model_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('catalog_variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devices_catalog_manufacturer_id'), 'devices', ['catalog_manufacturer_id'], unique=False)
    op.create_index(op.f('ix_devices_catalog_model_id'), 'devices', ['catalog_model_id'], unique=False)
    op.create_index(op.f('ix_devices_catalog_variant_id'), 'devices', ['catalog_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_catalog_variant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_catalog_model_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_catalog_manufacturer_id'), table_name='devices')
    op.drop_column('devices', 'catalog_variant_id')
    op.drop_column('devices', 'catalog_model_id')
    op.drop_column('devices', 'catalog_manufacturer_id')
    # ### end Alembic commands ###
