"""add total_cost and created_by to ticket_parts

Revision ID: 511b87626f27
Revises: dfc1f9075a17
Create Date: 2025-11-26 20:41:11.890019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "511b87626f27"
down_revision: Union[str, None] = "dfc1f9075a17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - adjusted ###

  # Cambio de tipo en part_movements.state (si lo quieres conservar)
  op.alter_column(
      "part_movements",
      "state",
      existing_type=mysql.INTEGER(),
      type_=mysql.TINYINT(display_width=1),
      existing_nullable=False,
      existing_server_default=sa.text("'1'"),
  )

  # OJO: NO tocamos ix_part_movements_part_id porque está usado por una FK.
  # También podemos vivir sin el índice nuevo sobre id, pero como Alembic lo generó,
  # lo dejamos porque no molesta.
  op.create_index(
      op.f("ix_part_movements_id"),
      "part_movements",
      ["id"],
      unique=False,
  )

  # 1) Añadimos las columnas nuevas en ticket_parts
  op.add_column(
      "ticket_parts",
      sa.Column("total_cost", sa.Numeric(precision=12, scale=2), nullable=True),
  )
  op.add_column(
      "ticket_parts",
      sa.Column("created_by_id", sa.Integer(), nullable=True),
  )
  op.create_index(
      op.f("ix_ticket_parts_created_by_id"),
      "ticket_parts",
      ["created_by_id"],
      unique=False,
  )
  op.create_foreign_key(
      "fk_ticket_parts_created_by",
      "ticket_parts",
      "users",
      ["created_by_id"],
      ["id"],
      onupdate="CASCADE",
      ondelete="SET NULL",
  )

  # 2) Rellenamos total_cost para los registros existentes
  op.execute(
      "UPDATE ticket_parts SET total_cost = qty * unit_price_snapshot"
  )

  # 3) Marcamos total_cost como NOT NULL ahora que ya tiene datos
  op.alter_column(
      "ticket_parts",
      "total_cost",
      existing_type=sa.Numeric(precision=12, scale=2),
      nullable=False,
  )

  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - adjusted ###

  # Revertimos cambios en ticket_parts
  op.drop_constraint(
      "fk_ticket_parts_created_by", "ticket_parts", type_="foreignkey"
  )
  op.drop_index(
      op.f("ix_ticket_parts_created_by_id"),
      table_name="ticket_parts",
  )
  op.drop_column("ticket_parts", "created_by_id")
  op.drop_column("ticket_parts", "total_cost")

  # Revertimos cambios en part_movements:
  # - quitamos el índice nuevo sobre id
  # - devolvemos el tipo original de state
  op.drop_index(
      op.f("ix_part_movements_id"),
      table_name="part_movements",
  )
  op.alter_column(
      "part_movements",
      "state",
      existing_type=mysql.TINYINT(display_width=1),
      type_=mysql.INTEGER(),
      existing_nullable=False,
      existing_server_default=sa.text("'1'"),
  )

  # Importante: NO recreamos ix_part_movements_part_id porque nunca lo borramos.
  # ### end Alembic commands ###
